[package]
name = "openwhoop-android-algos"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.40"
jni = "0.21.1"
openwhoop-algos = { git = "https://github.com/AlexBabai/openwhoop.git" }
openwhoop-codec = { git = "https://github.com/AlexBabai/openwhoop.git" }
