[package]
name = "openwhoop-android-algos"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.40"
jni = "0.21.1"
openwhoop-algos = { path = "../../third_party/openwhoop/src/openwhoop-algos" }
openwhoop-codec = { path = "../../third_party/openwhoop/src/openwhoop-codec" }
